WALL:
- id: 0
  start:
    x: -4.452
    y: -4.816
  end:
    x: -5.141
    y: -6.661
  angle: -1.928
  length: 1.969
- id: 1
  start:
    x: -4.081
    y: -3.897
  end:
    x: 0.6
    y: -5.7
  angle: -0.393
  length: 5.211
- id: 2
  start:
    x: 1.1
    y: -6.6
  end:
    x: 0.3
    y: -8.811
  angle: -1.929
  length: 1.905
