WALL:
- id: 0
  start:
    x: -1.941
    y: 2.023
  end:
    x: 1.979
    y: 1.984
  angle: -0.01
  length: 3.92
- id: 1
  start:
    x: -1.895
    y: 0.692
  end:
    x: -1.514
    y: 1.759
  angle: 1.228
  length: 1.133
- id: 2
  start:
    x: 0.081
    y: 0.222
  end:
    x: 1.916
    y: 0.674
  angle: 0.242
  length: 1.89
- id: 3
  start:
    x: -0.109
    y: -0.767
  end:
    x: -1.116
    y: -0.477
  angle: 2.861
  length: 1.048
